# whitelist
branches:
  only:
    - wporg

language: php

php:
  - 5.2
  - 5.3
  - 5.4
  - 5.5
  - 5.6

sudo: false

cache:
- bundler
- apt

addons:
  apt:
    packages:
    - ruby

install: gem install nyx

script:
    - nyx check:php .



notifications:
  email:
    on_success: never
    on_failure: change

env:
  - WP_VERSION=latest WP_MULTISITE=0

matrix:
  include:
    - php: 5.3
      env: WP_VERSION=latest WP_MULTISITE=0

before_script:
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION

script: phpunit
